services:
  welcome:
    image: liuuner/welcome
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.welcome.loadbalancer.server.port=80"
      - "traefik.http.routers.welcome.rule=(Host(`liuuner.ch`) || Host(`ads.liuuner.ch`))"
      - "traefik.http.routers.welcome.entrypoints=websecure"
      - "traefik.http.routers.welcome.tls.certresolver=letsencrypt"
    restart: unless-stopped
    deploy:
      replicas: 1
      update_config:
        order: start-first
